export const allLiveMatches = [
  {
    id: 12,
    team1: "Chelsea",
    team2: "Arsenal",
    score: "3 - 3",
    time: "90+4'",
    logo1: "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg",
    logo2: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
    league: "Premier League",
    pulseStatus: "Absolute Chaos",
    pulseEmoji: "🤯",
    pulseColor: "text-orange-500",
    insight: "Stamford Bridge is erupting after a 94th minute equalizer! VAR checking for offside.",
    emotionalMvp: "Palmer",
    polarizingPlayer: "Jackson",
    fanMood: "Hysterical",
    fanMoodEmoji: "🤯",
    metrics: { chaos: 100, tactical: 60, rivalry: 100, surprise: 90 },
    bookmarked: true,
    agenda: "VAR Check / Absolute Chaos",
    volatility: 100,
    triggers: ["[94' EQUALIZER]", "[VAR CHECK]"]
  },
  {
    id: 13,
    team1: "Newcastle",
    team2: "Spurs",
    score: "4 - 1",
    time: "80'",
    logo1: "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg",
    logo2: "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg",
    league: "Premier League",
    pulseStatus: "Humiliation",
    pulseEmoji: "💀",
    pulseColor: "text-coral",
    insight: "Spurs high line completely exposed. Fanbase in meltdown mode.",
    emotionalMvp: "Isak",
    polarizingPlayer: "Romero",
    fanMood: "Toxic",
    fanMoodEmoji: "🤬",
    metrics: { chaos: 85, tactical: 30, rivalry: 80, surprise: 95 },
    bookmarked: true,
    agenda: "High Line Exposed / Fan Meltdown",
    volatility: 92,
    triggers: ["[RED CARD]", "[PENALTY CLAIM]"]
  },
  {
    id: 1,
    team1: "Liverpool",
    team2: "Man City",
    score: "1 - 2",
    time: "74'",
    logo1: "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
    logo2: "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    league: "Premier League",
    pulseStatus: "Volatile",
    pulseEmoji: "⚡",
    pulseColor: "text-coral",
    insight: "Liverpool fans have grown frustrated with the midfield after repeated turnovers.",
    emotionalMvp: "De Bruyne",
    polarizingPlayer: "Mac Allister",
    fanMood: "Anxious",
    fanMoodEmoji: "😬",
    metrics: { chaos: 95, tactical: 80, rivalry: 90, surprise: 40 },
    bookmarked: true,
    agenda: "Midfield Capitulation / Tension Spiking",
    volatility: 95,
    triggers: ["[82' RED CARD]", "[VAR DISALLOWED GOAL]"]
  },
  {
    id: 2,
    team1: "Real Madrid",
    team2: "Barcelona",
    score: "2 - 2",
    time: "82'",
    logo1: "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    logo2: "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg",
    league: "La Liga",
    pulseStatus: "Heating Up",
    pulseEmoji: "🔥",
    pulseColor: "text-coral",
    insight: "Fans are split on Vinicius despite his assist.",
    emotionalMvp: "Bellingham",
    polarizingPlayer: "Vinicius Jr",
    fanMood: "Electric",
    fanMoodEmoji: "🤩",
    metrics: { chaos: 85, tactical: 85, rivalry: 99, surprise: 30 },
    bookmarked: true,
    agenda: "Vinicius Backlash / Boiling Point",
    volatility: 88,
    triggers: ["[CROWD UNREST]"]
  },
  {
    id: 3,
    team1: "Arsenal",
    team2: "Bayern",
    score: "0 - 0",
    time: "45'",
    logo1: "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
    logo2: "https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_München_logo_%282017%29.svg",
    league: "Champions League",
    pulseStatus: "Tense",
    pulseEmoji: "😬",
    pulseColor: "text-blue-400",
    insight: "Nervous energy dominates the Emirates.",
    emotionalMvp: "Saliba",
    polarizingPlayer: "Havertz",
    fanMood: "Nervous",
    fanMoodEmoji: "😰",
    metrics: { chaos: 40, tactical: 95, rivalry: 70, surprise: 20 },
    bookmarked: false,
    agenda: "Tactical Stalemate / Nervous Energy",
    volatility: 42,
    triggers: ["[0 SHOTS ON TARGET]"]
  },
  {
    id: 7,
    team1: "Aston Villa",
    team2: "Ajax",
    score: "3 - 0",
    time: "60'",
    logo1: "https://a.espncdn.com/i/teamlogos/soccer/500/362.png",
    logo2: "https://upload.wikimedia.org/wikipedia/en/7/79/Ajax_Amsterdam.svg",
    league: "Europa Conference League",
    pulseStatus: "Domination",
    pulseEmoji: "🔥",
    pulseColor: "text-green-400",
    insight: "Villa Park is rocking. Complete surprise demolition.",
    emotionalMvp: "Watkins",
    polarizingPlayer: "Henderson",
    fanMood: "Euphoric",
    fanMoodEmoji: "🎉",
    metrics: { chaos: 70, tactical: 60, rivalry: 40, surprise: 98 },
    bookmarked: false,
    agenda: "Total Demolition / Euphoria",
    volatility: 75,
    triggers: ["[HAT-TRICK HERO]"]
  }
];
