-- Matches Table
CREATE TABLE matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team1_name TEXT NOT NULL,
    team2_name TEXT NOT NULL,
    team1_logo TEXT NOT NULL,
    team2_logo TEXT NOT NULL,
    score TEXT DEFAULT '0 - 0',
    match_time TEXT DEFAULT '0''',
    league TEXT NOT NULL,
    pulse_status TEXT NOT NULL,
    pulse_emoji TEXT,
    pulse_color TEXT,
    insight TEXT,
    emotional_mvp TEXT,
    polarizing_player TEXT,
    fan_mood TEXT,
    fan_mood_emoji TEXT,
    chaos_metric INT DEFAULT 50,
    tactical_metric INT DEFAULT 50,
    rivalry_metric INT DEFAULT 50,
    surprise_metric INT DEFAULT 50,
    agenda TEXT,
    volatility INT DEFAULT 50,
    status TEXT DEFAULT 'live', -- 'live', 'upcoming', 'finished'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Match Events Table
CREATE TABLE match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
    event_type TEXT NOT NULL, -- 'GOAL', 'RED_CARD', 'VAR_CHECK', 'CROWD_UNREST', 'SHOT'
    event_time TEXT NOT NULL,
    description TEXT NOT NULL,
    impact_score INT DEFAULT 0, -- How much it affects volatility/chaos
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_events ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access on matches" ON matches FOR SELECT USING (true);
CREATE POLICY "Allow public read access on match_events" ON match_events FOR SELECT USING (true);

-- Allow authenticated users to insert/update (for admin/demo purposes)
CREATE POLICY "Allow authenticated insert matches" ON matches FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated update matches" ON matches FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Allow authenticated insert match_events" ON match_events FOR INSERT WITH CHECK (auth.role() = 'authenticated');
